import '../globals.css'
import React from 'react';

export const metadata = {
  title: 'Avni Piro Portfolio',
  description: 'Generated by Next + Sanity',
}

export default function RootLayout({
  children,

}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}