import React from 'react';
import Head from 'next/head';
import '../styles/globals.css'

export const metadata = {
  title: 'Avni Piro Portfolio',
  description: 'Generated by Next + Sanity',
};

export default function RootLayout({ children }) {
  return (
    
      <html lang="en">
        <body>{children}</body>
      </html>
  
   
  );
}
