import React from 'react';
import Head from 'next/head';
import '../globals.css';

export const metadata = {
  title: 'Avni Piro Portfolio',
  description: 'Generated by Next + Sanity',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content={metadata.description} />
        <title>{metadata.title}</title>
      </Head>
      <body>{children}</body>
    </html>
  );
}
